import { describe, expect, it } from "vitest";
import { deriveScenarios, isSubstantiveSection } from "./derived-scenarios";
import { normalizePracticeContext } from "./validation";
import { DeterministicEvaluator } from "../evaluation/deterministic-evaluator";
import { isPracticeContext } from "../evaluation/validation";
import type { ReferenceFact } from "./reference-source";

const fact = (id: string, question: string, answer: string): ReferenceFact => ({
  id, question, answer, keywords: question.toLowerCase().match(/[a-z0-9]{3,}/g) ?? [], source: "faq",
});

const tradingFaq = [
  fact("source-fact-1", "How do I register as an affiliate?", "To register as an affiliate, submit the application form from your dashboard, provide your payout details, and wait for the compliance review, which takes up to 3 business days."),
  fact("source-fact-2", "What is the affiliate commission structure?", "Affiliates earn 15 percent of the net trading profits generated by referred clients, paid monthly, with a minimum payout of 100 dollars."),
  fact("source-fact-3", "When are affiliate commission payments paid?", "Affiliate commission payments are paid on the first business day of each month to your registered payout account."),
  fact("source-fact-4", "How do I log in to the trading platform?", "Log in with your registered email and password on the platform page, complete the two-factor code from your authenticator app, and select your account type."),
  fact("source-fact-5", "Contact us", "Email us."),
  fact("source-fact-6", "Reference detail 9", "Some extracted paragraph that has no heading of its own and enough words to look substantive at first glance."),
];

describe("deriveScenarios", () => {
  it("suggests a drill per substantive FAQ section, skipping site furniture and placeholders", () => {
    const scenarios = deriveScenarios(tradingFaq);
    const titles = scenarios.map((scenario) => scenario.title);
    expect(titles).toContain("How do I register as an affiliate");
    expect(titles).toContain("What is the affiliate commission structure");
    expect(titles).toContain("How do I log in to the trading platform");
    expect(titles.some((title) => /contact/i.test(title))).toBe(false);
    expect(scenarios.every((scenario) => scenario.id.startsWith("derived-"))).toBe(true);
  });

  it("is deterministic: the same facts always produce the same ids and definitions", () => {
    const first = deriveScenarios(tradingFaq);
    const second = deriveScenarios(tradingFaq.map((f) => ({ ...f })));
    expect(second).toEqual(first);
  });

  it("groups sections whose headings share at least two significant words", () => {
    const scenarios = deriveScenarios(tradingFaq);
    const commission = scenarios.find((scenario) => /commission structure/i.test(scenario.title));
    expect(commission?.factIds).toContain("source-fact-3");
    expect(commission?.factIds).not.toContain("source-fact-4");
  });

  it("writes a natural customer persona and opening line from the section kind", () => {
    const scenarios = deriveScenarios(tradingFaq);
    const register = scenarios.find((scenario) => /register as an affiliate/i.test(scenario.title));
    expect(register?.openingLine).toMatch(/walk me through it\?$/i);
    expect(register?.customerPersona).toMatch(/trying to register as an affiliate/i);
    const login = scenarios.find((scenario) => /log in to the trading platform/i.test(scenario.title));
    expect(login?.openingLine).toContain("log in to the trading platform");
  });

  it("caps suggestions and never suggests thin sections", () => {
    expect(deriveScenarios(tradingFaq).length).toBeLessThanOrEqual(6);
    expect(isSubstantiveSection(fact("x", "Contact us", "Email us."))).toBe(false);
    expect(isSubstantiveSection(fact("x", "Reference detail 2", "Enough words here to pass the answer gate but the heading is a placeholder."))).toBe(false);
    expect(isSubstantiveSection(tradingFaq[0])).toBe(true);
  });

  it("keeps experience notes out of every suggestion", () => {
    const withNote = [...tradingFaq, fact("note-1", "Coach note?", "A personal coaching note with plenty of words to look like a real section at first glance.")];
    const scenarios = deriveScenarios(withNote);
    expect(scenarios.every((scenario) => scenario.factIds.every((id) => !id.startsWith("note-")))).toBe(true);
  });

  it("combines selected FAQ scenarios into one grounded practice session", () => {
    const sourceText = tradingFaq.map((item) => `Q: ${item.question}\nA: ${item.answer}`).join("\n\n");
    const base = normalizePracticeContext({
      source: { kind: "pasted-text", text: sourceText, confirmation: "confirmed" },
      sourceLabel: "Equity Edge",
      notes: [],
      scenarioId: "late-delivery",
    });
    const [first, second] = deriveScenarios(base.facts);
    const context = normalizePracticeContext({
      source: { kind: "pasted-text", text: sourceText, confirmation: "confirmed" },
      sourceLabel: "Equity Edge",
      notes: [],
      scenarioIds: [first.id, second.id],
    });

    expect(context.scenario.id).toBe(`multi-${first.id}~${second.id}`);
    expect(context.scenario.factIds).toEqual(expect.arrayContaining([...first.factIds, ...second.factIds]));
    expect(context.scenario.openingLine).toBe(first.openingLine);
    expect(context.scenario.title).toContain(first.title);
    expect(isPracticeContext(JSON.parse(JSON.stringify(context)))).toBe(true);
  });

  it("never suggests newsletter or FAQ-banner furniture sections", () => {
    const furniture = [
      ...tradingFaq,
      fact("source-fact-nl", "Subscribe to our newsletter", "Send copyright 2025 Equity Edge Ltd All rights reserved for the newsletter subscription."),
      fact("source-fact-faq", "Frequently Asked Questions", "General trading rules evaluation questions funded traders instant accounts and more in one long blob of text."),
    ];
    const titles = deriveScenarios(furniture).map((scenario) => scenario.title);
    expect(titles.some((title) => /newsletter/i.test(title))).toBe(false);
    expect(titles.some((title) => /frequently asked/i.test(title))).toBe(false);
  });
});

describe("derived scenarios end to end", () => {
  const faqText = [
    "Q: How do I register as an affiliate?",
    "A: To register as an affiliate, submit the application form from your dashboard and provide your payout details.",
    "",
    "Q: What is the affiliate commission structure?",
    "A: Affiliates earn 15 percent of net trading profits from referred clients, paid monthly.",
  ].join("\n");

  const base = normalizePracticeContext({
    source: { kind: "pasted-text", text: faqText, confirmation: "confirmed" },
    sourceLabel: "Equity Edge",
    notes: [],
    scenarioId: "late-delivery",
  });
  const derived = deriveScenarios(base.facts);
  const affiliate = derived.find((scenario) => /affiliate/i.test(scenario.title)) ?? derived[0];

  it("credits a verbatim answer inside a derived scenario", async () => {
    const context = normalizePracticeContext({
      source: { kind: "pasted-text", text: faqText, confirmation: "confirmed" },
      sourceLabel: "Equity Edge",
      notes: [],
      scenarioId: affiliate.id,
    });
    expect(context.scenario.id).toBe(affiliate.id);
    expect(context.scenario.factIds.length).toBeGreaterThan(0);

    const report = await new DeterministicEvaluator(context.sourceProvenance).evaluate({
      ...context,
      transcript: [{
        id: "t1", speaker: "trainee", text: "To register as an affiliate, submit the application form from your dashboard and provide your payout details.",
        source: "live-transcript", startedAt: "2026-09-18T10:00:00.000Z", endedAt: "2026-09-18T10:00:05.000Z",
      }],
    });
    expect(report.scores.factualAccuracy).toBeGreaterThan(0);
    expect(report.practice?.facts.length).toBeGreaterThan(0);
  });

  it("survives the session round-trip validation for stored contexts", () => {
    const context = normalizePracticeContext({
      source: { kind: "pasted-text", text: faqText, confirmation: "confirmed" },
      sourceLabel: "Equity Edge",
      notes: [],
      scenarioId: affiliate.id,
    });
    expect(isPracticeContext(JSON.parse(JSON.stringify(context)))).toBe(true);
  });
});
