import { describe, expect, it } from "vitest";
import { verifyGroundedPairs } from "./grounding";

describe("verifyGroundedPairs", () => {
  const source = "To register as an affiliate, submit the application form from your dashboard, provide your payout details, and wait for the compliance review, which takes up to 3 business days. Affiliates earn 15 percent of the net trading profits generated by referred clients, paid monthly.";

  it("keeps a pair whose answer is stated in the source", () => {
    const pairs = [{
      question: "How do I register as an affiliate?",
      answer: "Submit the application form from your dashboard, provide your payout details, and wait for the compliance review.",
    }];
    expect(verifyGroundedPairs(pairs, source)).toEqual(pairs);
  });

  it("drops a hallucinated answer whose words never appear in the source", () => {
    const pairs = [{
      question: "Do you guarantee funding?",
      answer: "Yes, we guarantee funding for every trader who signs up instantly.",
    }];
    expect(verifyGroundedPairs(pairs, source)).toEqual([]);
  });

  it("drops answers that are too short to be real content", () => {
    const pairs = [{ question: "What is slippage?", answer: "Slippage" }];
    expect(verifyGroundedPairs(pairs, source)).toEqual([]);
  });

  it("drops an answer that only partially exists in the source", () => {
    const pairs = [{
      question: "How do I register as an affiliate?",
      answer: "Submit the application form from your dashboard and pay the registration fee by bank transfer.",
    }];
    expect(verifyGroundedPairs(pairs, source)).toEqual([]);
  });

  it("keeps a question rephrased by the model when over half its terms come from the source", () => {
    const pairs = [{
      question: "Tell me about the affiliate payout details and compliance review",
      answer: "Provide your payout details, and wait for the compliance review, which takes up to 3 business days.",
    }];
    expect(verifyGroundedPairs(pairs, source)).toEqual(pairs);
  });

  it("keeps numeric conditions exactly as the source states them", () => {
    const pairs = [{
      question: "What are the payout terms?",
      answer: "15 percent of the net trading profits, paid monthly.",
    }];
    expect(verifyGroundedPairs(pairs, source)).toEqual(pairs);
  });

  it("rejects wrong numbers even when the rest of the sentence matches", () => {
    const pairs = [{
      question: "What are the payout terms?",
      answer: "15 percent of the net trading profits, paid within 60 days.",
    }];
    expect(verifyGroundedPairs(pairs, source)).toEqual([]);
  });
});
